### PR TITLE
Update haproxy load balancer README.md

### PR DESCRIPTION
**Pull request by jensuzleonard**
updates to haproxy load balancer to increase readability and referencing ability

### CODE REVIEW

**Comment by bcleonard** [comment]
I like all the changes except the last change (bottom of file).   The end is supposed to be about what its tested on and you changed it on how to run it (which is what was in the previous section)

**Comment by jensuzleonard** [comment]
Okay.  I will change it back.

**Review by bcleonard — COMMENTED** [review]
need docker-compose as a prerequisite.   Its a seperate program that docker.

**Comment by bcleonard** [comment]
approved

**Pull request closed without merging**
